# Copyright 2015 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# contrib_plugin(
#   name='plugin',
#   dependencies=[
#     'contrib/twitter-common-pants/src/python/twitter/common/pants/jvm/args:plugin',
#     'src/python/pants/goal:task_registrar',
#   ],
#   distribution_name='pantsbuild.pants.twitter.common.pants',
#   description='Pants plugins from twitter.commons',
#   additional_classifiers=[
#     'Topic :: Software Development :: Code Generators'
#   ],
#   register_goals=True,
# )

# python_library(
#   name='plugins',
#   dependencies=[
#     'pants-plugins/src/python/twitter/common/pants/jvm/args:plugin'
#   ],
#   provides = setup_py(
#     name = 'twitter.common.pants',
#     version = '0.8.3',
#     description = 'twitter.common plugins for the pants build system.',
#     long_description = read_contents('CHANGELOG.rst'),
#     url = 'https://github.com/twitter/commons',
#     license = 'Apache License, Version 2.0',
#     zip_safe = True,
#     classifiers = [
#       'Intended Audience :: Developers',
#       'License :: OSI Approved :: Apache Software License',
#       'Operating System :: OS Independent',
#       'Programming Language :: Python',
#     ]
#   )
# )
