#!/usr/bin/env bash

# Convenient shortcut script for updating an existing Pants rbt review:
#
# ./rbt-update <RB_ID> [other flags]
#
# will update the existing review, passing the flags through to rbt.

./rbt post -o -r "$@"
