#!/usr/bin/env bash

# Convenient shortcut script for creating a new Pants rbt review:
#
# ./rbt-create <name> ... <name> <other flags>
#
# will create a review with the specified names as reviewers, with pants-reviews as a group,
# and with the other flags passed through to rbt.

NAME_REGEX="^[a-zA-Z][a-zA-Z_.-]+$"
REVIEWERS=""

while [[ $1 ]] && [[ $1 =~ ${NAME_REGEX} ]]; do
  REVIEWERS="${REVIEWERS},$1"
  shift
done

REVIEWERS=${REVIEWERS:1}  # Strip leading comma.

if [[ ${REVIEWERS} ]]; then
  REVIEWERS_FLAG="--target-people=${REVIEWERS}"
fi

while :; do
  categories=( "API Change" "Bugfix" "New Feature" "Small Improvement" )
  echo "Choose a category for this patch:"
  echo ""
  for (( i=0; i < ${#categories[@]}; i++)); do
    echo "  ${i}: ${categories[$i]}"
  done
  echo ""
  read -p "Chosen category: " chosen

  if [ ${chosen} -lt 0 -o ${chosen} -gt ${#categories[@]} ]; then
    echo ""
    echo "Sorry, '${chosen}' isn't a valid choice."
    echo ""
  else
    # The value is good
    break
  fi
done

# FIXME: this is fairly crude, and doesn't exactly replicate the logic used by `rbt`.
SUMMARY_GUESS=`git show -s --pretty=format:%B | head -1`

./rbt post -o -g ${REVIEWERS_FLAG} --summary "[${categories[$chosen]}] ${SUMMARY_GUESS}" "$@"
