#!/usr/bin/env bash

# Convenient shortcut script for creating a new Pants rbt review:
#
# ./rbt-create <name> ... <name> <other flags>
#
# will create a review with the specified names as reviewers, with pants-reviews as a group,
# and with the other flags passed through to rbt.

NAME_REGEX="^[a-zA-Z][a-zA-Z_.-]+$"
REVIEWERS=""

while [[ $1 ]] && [[ $1 =~ ${NAME_REGEX} ]]; do
  REVIEWERS="${REVIEWERS},$1"
  shift
done

REVIEWERS=${REVIEWERS:1}  # Strip leading comma.

if [[ ${REVIEWERS} ]]; then
  REVIEWERS_FLAG="--target-people=${REVIEWERS}"
fi

while :; do
  categories=( "API Change" "Bugfix" "New Feature" "Small Improvement" )
  echo "Categories help the pants releasers build a proper changelog, highlighting your improvement. The possible categories are:"
  echo ""
  for (( i=0; i < ${#categories[@]}; i++)); do
    echo "  ${i}: ${categories[$i]}"
  done
  echo ""
  read -p "Choose a category for this change: " chosen

  if [ ${chosen} -lt 0 -o ${chosen} -gt ${#categories[@]} ]; then
    echo ""
    echo "Sorry, '${chosen}' isn't a valid choice."
    echo ""
  else
    # The value is good
    break
  fi
done

DEFAULT_TESTING=$(cat <<EOM
Tested in CI: <paste Travis CI URL>

Manual testing steps: <insert here, if any>

Changelog category: ${categories[$chosen]}
EOM)

./rbt post -o -g ${REVIEWERS_FLAG} --testing-done "${DEFAULT_TESTING}" "$@"
